# Generated by Django 4.1.2 on 2022-11-18 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company_phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='invoice_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='invoice_country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='invoice_postal_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='invoice_town',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='private_phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tax_number',
        ),
        migrations.CreateModel(
            name='PrivatePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefonszám')),
                ('invoice_postal_code', models.CharField(max_length=10, verbose_name='Irányítószám')),
                ('invoice_town', models.CharField(max_length=50, verbose_name='Város')),
                ('invoice_address', models.CharField(max_length=150, verbose_name='Utca, házszám')),
                ('invoice_country', models.CharField(max_length=50, verbose_name='Ország')),
                ('last_name', models.CharField(max_length=50, verbose_name='Vezetéknén')),
                ('first_name', models.CharField(max_length=50, verbose_name='Keresztnév')),
                ('is_private_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Cég neve')),
                ('company_phone_number', models.CharField(max_length=50, verbose_name='Telefonszám')),
                ('tax_number', models.CharField(max_length=50, verbose_name='Adószám')),
                ('invoice_postal_code', models.CharField(max_length=10, verbose_name='Irányítószám')),
                ('invoice_town', models.CharField(max_length=50, verbose_name='Város')),
                ('invoice_address', models.CharField(max_length=150, verbose_name='Utca, házszám')),
                ('invoice_country', models.CharField(max_length=50, verbose_name='Ország')),
                ('is_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
