# Generated by Django 4.1.2 on 2022-11-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_private_person',
        ),
    ]
