# Generated by Django 4.1.2 on 2022-11-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_is_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_private_person',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
