# Generated by Django 4.1.2 on 2022-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_is_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_company',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_private_person',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
